### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ArthurConan** [huanzhang12/ZOO-Attack#3]
I tried to execute attack on ImageNet with first example command:
python3 test_all.py --untargeted -a black -d imagenet -n 150 --solver adam -b 1 -c 10.0 --use_resize --reset_adam -m 1500 -p 10 -s "imagenet_untargeted"

Can anyone help me with error. Don't know what to do. Thanks in advance.

Traceback (most recent call last):
  File "test_all.py", line 262, in <module>
    main(args)
  File "test_all.py", line 102, in main
    data, model = ImageNet(), InceptionModel(sess, use_log)
  File "/root/Documents/python/ZOO-Attack-master/setup_inception.py", line 223, in __init__
    create_graph()
  File "/root/Documents/python/ZOO-Attack-master/setup_inception.py", line 123, in create_graph
    FLAGS.model_dir, 'frozen_inception_v3.pb'), 'rb') as f:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'untargeted'

**Comment by huanzhang12** [comment]
I am aware of this issue, and will push a fix soon. This is caused by certain tensorflow versions. Thanks for reporting!

**Comment by huanzhang12** [comment]
@ArthurConan Can you try the latest commit and see if it solves this issue? Thanks!

**Comment by kakacharles10** [comment]
Hi Huan! Do you have the generated attack images of cifar-10?

**Comment by kakacharles10** [comment]
Also is it necessary to run the train_model.py before running the test_attack.py? Since I am running out of memory. Thanks a lot!

**Comment by huanzhang12** [comment]
Yes it is necessary to run train_model.py to train the models before you start the attack.
I don't have any images at this time, except for those ones presented in our paper.

**Comment by kakacharles10** [comment]
Thanks Huan! Do you know is there any online resource that has attack data that is available for downloading?

**Comment by Mah-SP** [comment]
Hello
I wasn’t able to achieve valid results and my distortion value is > 20.
I executed the attack on ImageNet with first example command: 
python3 test_all.py --untargeted -a black -d imagenet -n 150 --solver adam -b 1 -c 10.0 --use_resize --reset_adam -m 1500 -p 10 -s "imagenet_untargeted" 
I had to change some lines in setup_inception.py and test_.-all.py because I used tensorflow 2.3 and I wasn't able to downgrade it...
in addition I had to use a different image processing package:
Instead of using  "import scipy.misc" I had to use  --> from skimage.transform import resize
                                                                                   import imageio
It would be nice if you could help me to solve my problem :-)
Thanks in advance!
